apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://codeclarity-prometheus-dev:9090
    isDefault: true
    editable: true
    uid: prometheus
  - name: Loki
    type: loki
    access: proxy
    url: http://codeclarity-loki-dev:3100
    isDefault: false
    editable: true
    uid: loki